config/routes.rb
Rails.application.routes.draw do

  get 'urls/new'

  get 'urls/create'

  get 'urls/show'

  get 'info/home'

 devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

 resources :tastemakers
 resources :urls
 resources :posts
 resources :items
 resources :users
 resources :instagrams
 resources :guesses
 

 root to: "items#index"

get '/:code', to: 'urls#redirector'
get '/:code/preview', to: 'urls#preview'

 get "/get_instagram" => "instagrams#get_instagrams"

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/models/tastemaker.rb
class Tastemaker < ActiveRecord::Base
	has_many :posts
  has_many :comments
  
  # validates :title, :link, :category, :upvotes, presence: true

  # def self.popular
  #   where (tastemaker_counts_followed_by >= 100 || tastemaker_influence_score >= 5 || elite_tastemaker = true)
  # end

  # def self.recent
  #   where 'created_at >= ?', Date.today
  # end

  # def self.search_for(query)
  #   where('title LIKE :query OR category LIKE :query', query: "%#{query}%")
  # end

end

app/controllers/tastemakers_controller.rb
class TastemakersController < ApplicationController

  def index
  	@tastemakers = Tastemaker.all 
  end

  def show
    @tastemaker = Tastemaker.find(params[:id])
    @posts = @tastemaker.posts
  	# @post = Post.find(params[:id])
    # @posts = Posts.find_by(post_id: @post.id)
  end

  def create
  end

  def new
    @tastemaker = Tastemaker.new
  end

  def create
    @tastemaker = Tastemaker.new(tastemaker_params)
    if @tastemaker.save
      redirect_to @tastemaker, notice: "Fashionista was created!"
    else
      render 'new'
    end
  end

  def edit
    @tastemaker = Tastemaker.find(params[:id])
  end

  def update
    #why do i need to add this @tastemaker = Tastemaker.find(params[:id]).  Doesn't the @ make this a global varieble.
    @tastemaker = Tastemaker.find(params[:id])
    if @tastemaker.update!(tastemaker_params)
      redirect_to @tastemaker, notice: "Fashionista was updated!  You are awesome!"
    else
      render 'edit'
    end
  end


  private

  def set_tastemaker
    @tastemaker = Tastemaker.find(params[:id])
  end

  def tastemaker_params
    params.require(:tastemaker).permit(:tastemaker_influence_score, :fashion_tastemaker, :elite_tastemaker)
  end


end

app/helpers/tastemakers_helper.rb
module TastemakersHelper
end

app/views/tastemakers/create.html.erb
<h1>Tastemakers#create</h1>
<p>Find me in app/views/tastemakers/create.html.erb</p>

app/views/tastemakers/index.html.erb
<h1>Tastemakers#index</h1>
<p>Find me in app/views/tastemakers/index.html.erb</p>



	<table class="table table-striped table-bordered table-condensed table-hover">
	    <thead>
	        <tr>
			  <th>Photo</th>
	          <th>Name / ID</th>
	          <th># of posts</th>
	          <th># of comments</th>
	          <th>influence score</th>
	          <th>fashion tastemaker</th>
	          <th>elite tastemaker</th>
	        </tr>
	    </thead>
	    <tbody>
	    <% @tastemakers.each do |indiv_tm| %>
	    	<%= simple_form_for indiv_tm do |f| %>
	        <tr>
			  <td><%= link_to tastemaker_path(indiv_tm) do %> 
              <%= image_tag "#{indiv_tm.tastemaker_profile_pict}" %>
              <% end %> </td>
	          <td><%= indiv_tm.tastemaker_full_name %> </br> 
	          	<%= indiv_tm.tastemaker_instagram_username %> </td>
	          <td><%= indiv_tm.posts.count %></td>
	          <td><%= indiv_tm.comments.count %></td>
	          <td><%= f.input :tastemaker_influence_score, label: false %></td>
	          <td><%= f.input :fashion_tastemaker, label: false %></td>
	          <td><%= f.input :elite_tastemaker, label: false, style:"padding-left: 40px;" %></td>
	          <td><%= link_to 'Show', tastemaker_path(indiv_tm) %></td>
	          <td><%= link_to 'Edit', edit_tastemaker_path(indiv_tm) %></td>
	          <td><%= link_to 'Destroy', tastemaker_path(indiv_tm), method: :delete, data: { confirm: 'Are you sure?' } %></td>
	        </tr>
	        <%end%>
	        <%end%>
	    </tbody>
	</table>

app/views/tastemakers/new.html.erb
<h1>Tastemakers#new</h1>
<p>Find me in app/views/tastemakers/new.html.erb</p>

app/views/tastemakers/show.html.erb
<div class = "col-md-7">
</br></br>
<h1><%="Tastemaker: #{@tastemaker.tastemaker_full_name}"%></h1>
<h2><%="Username: #{@tastemaker.tastemaker_instagram_username}"%></h1>
<p> <%="Instagram ID: #{@tastemaker.tastemaker_instagram_id}"%> </p>

</div>



<div class = "col-md-5">
</br></br>
                    <p> <%= simple_form_for @tastemaker do |f| %>
                        <p> <%= f.input :tastemaker_influence_score %> </p>
                        <p> <%= f.input :fashion_tastemaker %> </p>
                        <p> <%= f.input :elite_tastemaker %> </p>
                        <p> <%= f.submit %> </p>
                    <% end %>
</div>

	<% @posts.each do |indiv_post| %>
    	<div class ="row">
    		<div class = "col-md-5">
    				<%= link_to instagram_path(indiv_post) do %> 
              <%= image_tag "#{indiv_post.photo_standard_res}" %>
            <% end %>
    		</div>
    		<div class = "col-md-7">
  				<div class = "row">
                    <p> <%= "Number of likes #{indiv_post.likes}"%> </p>
                    <p> <%= "Number of comments #{indiv_post.comment_count}"%> </p>
  				</div>

                <div class = "row">
                    <p> <%= link_to indiv_post.link, indiv_post.link%> </p>
                </div>


  				<div class = "row"> 
            <table class="table table-striped table-bordered table-condensed">
                <thead>
                    <tr>
                        <th>Comment</th>
                        <th>Username</th>
                        <th>Confirmed?</th>
                    </tr>
                </thead>
                <tbody>
                  <% indiv_post.comments.each do |individ_comment| %>
                    <tr>
                        <td> <%= individ_comment.text_field%>       </td>
                        <td> <%= individ_comment.tastemaker.tastemaker_instagram_username%> </td>
                        <td> <%= individ_comment.confirmed_comment%>  </td>
                    </tr>
                    <%end%>
                </tbody>
            </table>

            <%#= render 'comments'%> 
  				</div>
    		</div>
    	</div>
    </br></br></br>
<%end%>
<%= @posts.count%>