config/routes.rb
Rails.application.routes.draw do

  get 'urls/new'

  get 'urls/create'

  get 'urls/show'

  get 'info/home'

 devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

 resources :tastemakers
 resources :urls
 resources :posts
 resources :items
 resources :users
 resources :instagrams
 resources :guesses
 

 root to: "items#index"

get '/:code', to: 'urls#redirector'
get '/:code/preview', to: 'urls#preview'

 get "/get_instagram" => "instagrams#get_instagrams"

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  classification   :string(255)
#  description      :string(255)
#  brand            :string(255)
#  url_link         :string(255)
#  product_id       :string(255)
#  image            :string(255)
#  price_web        :integer
#  created_at       :datetime
#  updated_at       :datetime
#  currently_active :boolean          default(TRUE)
#

class Item < ActiveRecord::Base
	has_and_belongs_to_many :posts
	has_many :guesses 	
	has_many :urls

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_action :set_item, only: [:new, :edit, :show, :update]
  # before_filter :user_signed_in?

  def index
    # @items = Item.search_for(params[:q])
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item, notice: "Fashion Item was created!"
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    #why do i need to add this @item = Item.find(params[:id]).  Doesn't the @ make this a global varieble.
    @item = Item.find(params[:id])
    if @item.update item_params
      redirect_to @item, notice: "Fashion Item was updated!"
    else
      render 'edit'
    end
  end

  def show
    @item = Item.find(params[:id])

    if @item.urls.count > 0
       @personalized_item_link = @item.urls.first

      else
          @userkey = current_user.id
          @hash = rand(50000..1000000)
          @hash_code = (@hash.to_s + "UUUUU".to_s + @userkey.to_s)
          @fulllink = ("http://localhost:3000/".to_s + @hash_code.to_s)
          # safe_url_params = params.require(:url).permit(:link)

          @personalized_item_link = @item.urls.create!({
              hash_code: @hash_code,
              user_id: current_user.id,
              link: @fulllink
              })
          # @url.save
        current_user.urls << @personalized_item_link
        @personalized_item_link.update({forwarding_link: @item.url_link})
      end
  end



  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :classification, :brand, :url_link, :product_id, :image, :price_web)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this fashion item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
   <%= f.label :name %><br>
   <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :classification %><br>
  <%= f.text_field :classification %>
</div>
<div class="field">
  <%= f.label :price_web %><br>
  <%= f.text_field :price_web %>
</div>
<div class="field">
  <%= f.label :currently_active %><br>
  <%= f.check_box :currently_active %>
</div>
 <div class="actions">
    <%= f.submit %>
 </div>
<% end %>


<%= link_to 'Back', items_path %>

app/views/items/_item_list.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Classification</th>
      <th>Web_Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.classification %></td>
        <td>$<%= item.price_web %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fashion Item', new_item_path %>

app/views/items/edit.html.erb
<h1>Edit Item / Product</h1>
<%#= render 'item_form' %>



	<div class = "col-md-5">
		<%= image_tag @item.image %>
	</div>
	<div class = "col-md-7">
		<%= simple_form_for @item  do |f| %>
		  <%= f.input :name %>
		  <%= f.input :classification, input_html: { maxlength: 30 } %>
		  <%= f.input :price_web%>
		  <%= f.input :url_link%>
		  <%= f.input :image%>
		  <%= f.input :currently_active %>
		<% end %>
	</div>

app/views/items/index.html.erb
this is the index for controller items

<h1>All the items in the product database!</h1>
<p><%= notice %></p>

<h3><%= link_to "+ Add New Fashion Item", new_item_path %></h3>

<%= form_tag items_path, method: "GET" do %>
  <%= text_field_tag :q, params[:q] %>
  <%= submit_tag "Search" %>
<% end %>

<br/>





  <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th>Photo</th>
                <th>Brand</th>
                <th>Name</th>
                <th>Mentions</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <% @items.each do |indiv_item| %>

            <tr>
              <td>  <%= link_to item_path(indiv_item) do %> 
                  <%= image_tag "#{indiv_item.image}", :class => "maximage" %>
                  <% end %></br> 
                  <%#= link_to 'www.localhost:3000/link/sdlkfjdljkfa', http://www.cnn.com %> </td>
              <td><%= indiv_item.name %></td>
              <td><%= indiv_item.classification %></td>
              <td><%= rand 10...70 %> </td>
              <td>$<%= indiv_item.price_web %></td>
              <td><%= link_to 'Show', indiv_item %></td>
              <td><%= link_to 'Edit', edit_item_path(indiv_item) %></td>
              <td><%= link_to 'Destroy', indiv_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <%end%>
        </tbody>
    </table>

app/views/items/new.html.erb
<h1>Create a New Fashion Item</h1>
<%= render 'item_form' %>

app/views/items/old_item_list.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Classification</th>
      <th>Web_Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.classification %></td>
        <td>$<%= item.price_web %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fashion Item', new_item_path %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<p><%= @item.classification %></p>


    		<div class = "col-md-5">
              <%= image_tag "#{@item.image}" %>
    		</div>
    		<div class = "col-md-7">
  				<div class = "row">
                    <%= simple_form_for @item do |f| %>
                      <%= f.input :description %>
                      <%= f.submit %>
                      <%= link_to "Edit", edit_item_path(@item) %>
                      <%= link_to 'Back', items_path %>
                  </br></br></br></br></br></br>
                    <% end %>
  				</div>

                <div class = "row">
					<p><%= "Item name: #{@item.name}" %></p>
					<p><%= "Item classification: #{@item.classification}" %></p>
					<p><%= "Item brand: #{@item.brand}" %></p>
					<p><%= "Item url: #{@item.url_link}" %></p>
          <p><%= "Your personallized URL for this item: "%>
            <%= link_to "#{@personalized_item_link.link}", "#{@personalized_item_link.forwarding_link}" %></p>


                </div>
    		</div>
    </br></br></br>