config/routes.rb
Rails.application.routes.draw do

  get 'urls/new'

  get 'urls/create'

  get 'urls/show'

  get 'info/home'

 devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

 resources :tastemakers
 resources :urls
 resources :posts
 resources :items
 resources :users
 resources :instagrams
 resources :guesses
 

 root to: "items#index"

get '/:code', to: 'urls#redirector'
get '/:code/preview', to: 'urls#preview'

 get "/get_instagram" => "instagrams#get_instagrams"

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
  <li><%= link_to "Login with Twitter", user_omniauth_authorize_path(:twitter) %> </li>
  <li><%= link_to "Login with Instagram", user_omniauth_authorize_path(:instagram) %> </li>

<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'Instagram Feed', posts_path %></li>
  <li><%= link_to 'Tastemakers', tastemakers_path %></li>
  <li><%= link_to 'Items Feed', items_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Photo Hunt" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Photo Hunt" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  <header>
    <%= render 'layouts/navigation' %>
  <main role="main">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </main>
  </header>
 </head>




  <body>


  </body>
</html>

app/views/layouts/oldapplication.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoHunt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">




<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <%= link_to "Login with Twitter", user_omniauth_authorize_path(:twitter), :class => 'navbar-link'  %>
  <%= link_to "Login with Instagram", user_omniauth_authorize_path(:instagram), :class => 'navbar-link'  %>
<% end %>

<%= yield %>

</body>
</html>